/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RadioGroupIndicator: typeof import('reka-ui')['RadioGroupIndicator']
    RadioGroupItem: typeof import('reka-ui')['RadioGroupItem']
    RadioGroupRoot: typeof import('reka-ui')['RadioGroupRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('reka-ui')['Separator']
  }
}
